### PR TITLE
Update define-map.md

### PR DESCRIPTION
**Pull request by frank-dspeed**
This adds basic information about the option argument

### CODE REVIEW

**Comment by phillipskevin** [comment]
You cannot pass `options` like this to the DefineMap constructor. This only works when creating a constructor using `DefineMap.extend`.

**Comment by justinbmeyer** [comment]
There is a `sealed` option just on `new DefineMap(props, sealed)`: https://github.com/canjs/can-define/blob/master/map/map.js#L79

**Comment by frank-dspeed** [comment]
@justinbmeyer there must be something wrong i pass sealed: false as first argument and it works like a charm

**Comment by justinbmeyer** [comment]
You likely passed that to extend, not to new DefineMap

**Pull request closed without merging**
