### PR TITLE
Add can-define/list/list.prototype.sort

### PR DESCRIPTION
**Pull request by marshallswain**
Complete with docs and tests.  It uses Array.prototype.sort on the list itself, so it allows sorting on dynamic define getter props.  🎉

### CODE REVIEW

**Comment by marshallswain** [comment]
Now uses list.replace() to make sure the events fire.  Tests updated to make sure that a stache template updates.

**Comment by justinbmeyer** [comment]
@marshallswain why does this test use can-stache?

**Comment by justinbmeyer** [comment]
I think this could have just used a compute ...

**Comment by marshallswain** [comment]
Only because that's how I thought to test it.

**Pull request merged**
